# Generated by Django 6.1 on 2026-08-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الكتاب')),
                ('author', models.CharField(max_length=100, verbose_name='اسم المؤلف')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='الرقم المعياري')),
                ('category', models.CharField(max_length=50, verbose_name='التصنيف')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='إجمالي النسخ')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='النسخ المتاحة')),
            ],
        ),
    ]
